### ISSUE TITLE
error on linting

### ISSUE THREAD

**Issue by Uncleseneca** [solid-soda/scripts#27]
Hi!
I try to lint my code and get the following error:

```
(node:48885) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dependencies' of null
    at contents.map.map.info (/Users/vladimirgolotin/work/danilovsky-web/node_modules/@solid-soda/scripts/utils/projectWithDependency.js:12:33)
    at Array.map (<anonymous>)
    at projectWithDependency (/Users/vladimirgolotin/work/danilovsky-web/node_modules/@solid-soda/scripts/utils/projectWithDependency.js:11:6)
    at checkSvelteProject (/Users/vladimirgolotin/work/danilovsky-web/node_modules/@solid-soda/scripts/utils/defineProjectPlugins.js:11:5)
    at defineProjectPlugins (/Users/vladimirgolotin/work/danilovsky-web/node_modules/@solid-soda/scripts/utils/defineProjectPlugins.js:50:5)
(node:48885) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:48885) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by igorkamyshev** [comment]
Hello, thanks for reporting. Please, provide repo with minimal code for reporoduce and your Node.js version.
